services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      # healthcheck 內部要使用 $$ 來引用容器內的環境變數
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - takao_network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - takao_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    restart: always
    volumes:
      - .:/code
      - web_venv:/code/.venv
    working_dir: /code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - takao_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    restart: always
    volumes:
      - .:/code
      - worker_venv:/code/.venv
    working_dir: /code
    command: sh -c "export PYTHONPATH=. && export DISPLAY=:99 && dramatiq app.workers:redis_broker app.workers --worker-shutdown-timeout 285000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - takao_network

networks:
  takao_network:
    driver: bridge

volumes:
  postgres_data:
  web_venv: {}      # [新增] 在檔案最下方宣告這個數據卷
  worker_venv: {}
