# fly.toml

app = 'cpbl-takao-today-be'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

# 原有的 [processes] 區塊保持不變
[processes]
  web = "uvicorn app.main:app --host 0.0.0.0 --port 8080"
  worker = "dramatiq app.tasks"

# 原有的 [[services]] 區塊是針對 web 程序的，保持不變
[[services]]
  processes = ["web"]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  # 確保 Web 服務永不休眠
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.checks]]
    type = "tcp"
    port = 8080
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

# --- 新增 ---
# 專門為 worker 程序設定服務與啟停策略
[[services]]
  processes = ["worker"]
  internal_port = 8081

  # 允許 worker 機器在閒置時自動關閉
  auto_stop_machines = true
  auto_start_machines = false # 我們將手動啟動它

  # 預設保持 0 台機器運行，以節省費用
  min_machines_running = 0
