# fly.toml

app = 'cpbl-takao-today-be'
primary_region = 'sin'

# [新增] 為所有 process 設定優雅關閉參數
# 當收到停止指令時，發送 SIGINT 信號
kill_signal = "SIGINT"
# 給予 10 分鐘 (600 秒) 的寬限時間，等待 process 處理完畢
kill_timeout = "600s"

[build]
  dockerfile = "Dockerfile"

[processes]
  web = "uvicorn app.main:app --host 0.0.0.0 --port 8080"
  # [修改] 為 dramatiq 指令加上內部超時，設定為 570 秒 (9.5 分鐘)，略小於平台的 kill_timeout
  worker = "dramatiq app.tasks --shutdown-timeout 570000"

[[services]]
  processes = ["web"]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.checks]]
 type = "tcp"
 port = 8080
 interval = "15s"
 timeout = "2s"
 grace_period = "30s"

  # 設定 HTTP 健康檢查
  [[services.http_checks]]
    # 每小時檢查一次
    interval = "1h"
    # 每次檢查的超時時間
    timeout = "30s"
    # 機器啟動後的寬限期
    grace_period = "30s"
    # 使用 GET 方法
    method = "get"
    # 指向我們新建的健康檢查端點
    path = "/api/system/health"
    # 使用 http 協定 (在 Fly.io 內部網路)
    protocol = "http"
    # 失敗後關閉機器
    restart_limit = 0
