"""Add player_career_stats table

Revision ID: 465fac3fc553
Revises: f876d5635457
Create Date: 2025-08-21 14:52:37.924061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "465fac3fc553"
down_revision: Union[str, None] = "f876d5635457"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_career_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("debut_date", sa.Date(), nullable=True),
        sa.Column("handedness", sa.String(), nullable=True),
        sa.Column("games_played", sa.Integer(), nullable=True),
        sa.Column("plate_appearances", sa.Integer(), nullable=True),
        sa.Column("at_bats", sa.Integer(), nullable=True),
        sa.Column("runs_scored", sa.Integer(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=True),
        sa.Column("singles", sa.Integer(), nullable=True),
        sa.Column("doubles", sa.Integer(), nullable=True),
        sa.Column("triples", sa.Integer(), nullable=True),
        sa.Column("homeruns", sa.Integer(), nullable=True),
        sa.Column("rbi", sa.Integer(), nullable=True),
        sa.Column("total_bases", sa.Integer(), nullable=True),
        sa.Column("strikeouts", sa.Integer(), nullable=True),
        sa.Column("walks", sa.Integer(), nullable=True),
        sa.Column("intentional_walks", sa.Integer(), nullable=True),
        sa.Column("hit_by_pitch", sa.Integer(), nullable=True),
        sa.Column("stolen_bases", sa.Integer(), nullable=True),
        sa.Column("caught_stealing", sa.Integer(), nullable=True),
        sa.Column("sacrifice_hits", sa.Integer(), nullable=True),
        sa.Column("sacrifice_flies", sa.Integer(), nullable=True),
        sa.Column("gidp", sa.Integer(), nullable=True),
        sa.Column("ground_outs", sa.Integer(), nullable=True),
        sa.Column("fly_outs", sa.Integer(), nullable=True),
        sa.Column("avg", sa.REAL(), nullable=True),
        sa.Column("obp", sa.REAL(), nullable=True),
        sa.Column("slg", sa.REAL(), nullable=True),
        sa.Column("ops", sa.REAL(), nullable=True),
        sa.Column("go_ao_ratio", sa.REAL(), nullable=True),
        sa.Column("sb_percentage", sa.REAL(), nullable=True),
        sa.Column("ops_plus", sa.REAL(), nullable=True),
        sa.Column("k_percentage", sa.REAL(), nullable=True),
        sa.Column("bb_percentage", sa.REAL(), nullable=True),
        sa.Column("bb_per_k", sa.REAL(), nullable=True),
        sa.Column("babip", sa.REAL(), nullable=True),
        sa.Column("bip_percentage", sa.REAL(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_career_stats_id"), "player_career_stats", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_player_career_stats_player_name"),
        "player_career_stats",
        ["player_name"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_player_career_stats_player_name"), table_name="player_career_stats"
    )
    op.drop_index(op.f("ix_player_career_stats_id"), table_name="player_career_stats")
    op.drop_table("player_career_stats")
    # ### end Alembic commands ###
