"""Add PlayerFieldingStatsDB table

Revision ID: 6988c26c5d7e
Revises: 8ca6f5022ea6
Create Date: 2025-09-01 04:13:55.397604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6988c26c5d7e"
down_revision: Union[str, None] = "8ca6f5022ea6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_fielding_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=True),
        sa.Column("games_played", sa.Integer(), nullable=True),
        sa.Column("total_chances", sa.Integer(), nullable=True),
        sa.Column("putouts", sa.Integer(), nullable=True),
        sa.Column("assists", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Integer(), nullable=True),
        sa.Column("double_plays", sa.Integer(), nullable=True),
        sa.Column("triple_plays", sa.Integer(), nullable=True),
        sa.Column("passed_balls", sa.Integer(), nullable=True),
        sa.Column("caught_stealing_catcher", sa.Integer(), nullable=True),
        sa.Column("stolen_bases_allowed_catcher", sa.Integer(), nullable=True),
        sa.Column("fielding_percentage", sa.REAL(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "player_name", "position", name="_player_position_fielding_uc"
        ),
    )
    op.create_index(
        op.f("ix_player_fielding_stats_id"),
        "player_fielding_stats",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_fielding_stats_player_name"),
        "player_fielding_stats",
        ["player_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_fielding_stats_position"),
        "player_fielding_stats",
        ["position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_player_fielding_stats_position"), table_name="player_fielding_stats"
    )
    op.drop_index(
        op.f("ix_player_fielding_stats_player_name"), table_name="player_fielding_stats"
    )
    op.drop_index(
        op.f("ix_player_fielding_stats_id"), table_name="player_fielding_stats"
    )
    op.drop_table("player_fielding_stats")
    # ### end Alembic commands ###
