"""Add is_score_from_description and incomplete_pa type

Revision ID: 8ca6f5022ea6
Revises: 465fac3fc553
Create Date: 2025-08-25 08:08:20.069403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ca6f5022ea6"
down_revision: Union[str, None] = "465fac3fc553"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "at_bat_details",
        sa.Column(
            "is_score_from_description",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("at_bat_details", "is_score_from_description")
    # ### end Alembic commands ###
