"""Initial migration

Revision ID: a41a40513d45
Revises:
Create Date: 2025-07-19 06:46:14.070127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a41a40513d45"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cpbl_game_id", sa.String(), nullable=True),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("game_time", sa.String(), nullable=True),
        sa.Column("home_team", sa.String(), nullable=False),
        sa.Column("away_team", sa.String(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("venue", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("winning_pitcher", sa.String(), nullable=True),
        sa.Column("losing_pitcher", sa.String(), nullable=True),
        sa.Column("save_pitcher", sa.String(), nullable=True),
        sa.Column("mvp", sa.String(), nullable=True),
        sa.Column("game_duration", sa.String(), nullable=True),
        sa.Column("attendance", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_date", "home_team", "away_team", name="_game_date_teams_uc"
        ),
    )
    op.create_index(
        op.f("ix_game_results_cpbl_game_id"),
        "game_results",
        ["cpbl_game_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_game_results_game_date"), "game_results", ["game_date"], unique=False
    )
    op.create_index(op.f("ix_game_results_id"), "game_results", ["id"], unique=False)
    op.create_table(
        "game_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.String(), nullable=True),
        sa.Column("game_date", sa.Date(), nullable=True),
        sa.Column("game_time", sa.String(), nullable=True),
        sa.Column("matchup", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_schedules_game_id"), "game_schedules", ["game_id"], unique=True
    )
    op.create_index(
        op.f("ix_game_schedules_id"), "game_schedules", ["id"], unique=False
    )
    op.create_table(
        "player_season_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=True),
        sa.Column("data_retrieved_date", sa.String(), nullable=True),
        sa.Column("games_played", sa.Integer(), nullable=True),
        sa.Column("plate_appearances", sa.Integer(), nullable=True),
        sa.Column("at_bats", sa.Integer(), nullable=True),
        sa.Column("runs_scored", sa.Integer(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=True),
        sa.Column("rbi", sa.Integer(), nullable=True),
        sa.Column("homeruns", sa.Integer(), nullable=True),
        sa.Column("singles", sa.Integer(), nullable=True),
        sa.Column("doubles", sa.Integer(), nullable=True),
        sa.Column("triples", sa.Integer(), nullable=True),
        sa.Column("total_bases", sa.Integer(), nullable=True),
        sa.Column("strikeouts", sa.Integer(), nullable=True),
        sa.Column("stolen_bases", sa.Integer(), nullable=True),
        sa.Column("gidp", sa.Integer(), nullable=True),
        sa.Column("sacrifice_hits", sa.Integer(), nullable=True),
        sa.Column("sacrifice_flies", sa.Integer(), nullable=True),
        sa.Column("walks", sa.Integer(), nullable=True),
        sa.Column("intentional_walks", sa.Integer(), nullable=True),
        sa.Column("hit_by_pitch", sa.Integer(), nullable=True),
        sa.Column("caught_stealing", sa.Integer(), nullable=True),
        sa.Column("ground_outs", sa.Integer(), nullable=True),
        sa.Column("fly_outs", sa.Integer(), nullable=True),
        sa.Column("avg", sa.REAL(), nullable=True),
        sa.Column("obp", sa.REAL(), nullable=True),
        sa.Column("slg", sa.REAL(), nullable=True),
        sa.Column("ops", sa.REAL(), nullable=True),
        sa.Column("go_ao_ratio", sa.REAL(), nullable=True),
        sa.Column("sb_percentage", sa.REAL(), nullable=True),
        sa.Column("silver_slugger_index", sa.REAL(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_season_stats_id"), "player_season_stats", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_player_season_stats_player_name"),
        "player_season_stats",
        ["player_name"],
        unique=True,
    )
    op.create_table(
        "player_game_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("team_name", sa.String(), nullable=True),
        sa.Column("batting_order", sa.String(), nullable=True),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("plate_appearances", sa.Integer(), nullable=True),
        sa.Column("at_bats", sa.Integer(), nullable=True),
        sa.Column("runs_scored", sa.Integer(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=True),
        sa.Column("doubles", sa.Integer(), nullable=True),
        sa.Column("triples", sa.Integer(), nullable=True),
        sa.Column("homeruns", sa.Integer(), nullable=True),
        sa.Column("rbi", sa.Integer(), nullable=True),
        sa.Column("walks", sa.Integer(), nullable=True),
        sa.Column("intentional_walks", sa.Integer(), nullable=True),
        sa.Column("hit_by_pitch", sa.Integer(), nullable=True),
        sa.Column("strikeouts", sa.Integer(), nullable=True),
        sa.Column("stolen_bases", sa.Integer(), nullable=True),
        sa.Column("caught_stealing", sa.Integer(), nullable=True),
        sa.Column("sacrifice_hits", sa.Integer(), nullable=True),
        sa.Column("sacrifice_flies", sa.Integer(), nullable=True),
        sa.Column("gidp", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Integer(), nullable=True),
        sa.Column("avg_cumulative", sa.REAL(), nullable=True),
        sa.Column("obp_cumulative", sa.REAL(), nullable=True),
        sa.Column("slg_cumulative", sa.REAL(), nullable=True),
        sa.Column("ops_cumulative", sa.REAL(), nullable=True),
        sa.Column("at_bat_results_summary", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_id", "player_name", "team_name", name="_game_player_uc"
        ),
    )
    op.create_index(
        op.f("ix_player_game_summary_id"), "player_game_summary", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_player_game_summary_player_name"),
        "player_game_summary",
        ["player_name"],
        unique=False,
    )
    op.create_table(
        "at_bat_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_game_summary_id", sa.Integer(), nullable=False),
        sa.Column("inning", sa.Integer(), nullable=True),
        sa.Column("sequence_in_game", sa.Integer(), nullable=True),
        sa.Column("result_short", sa.String(), nullable=True),
        sa.Column("result_description_full", sa.String(), nullable=True),
        sa.Column("opposing_pitcher_name", sa.String(), nullable=True),
        sa.Column("pitch_sequence_details", sa.String(), nullable=True),
        sa.Column("runners_on_base_before", sa.String(), nullable=True),
        sa.Column("outs_before", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["player_game_summary_id"],
            ["player_game_summary.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "player_game_summary_id", "sequence_in_game", name="_summary_seq_uc"
        ),
    )
    op.create_index(
        op.f("ix_at_bat_details_id"), "at_bat_details", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_at_bat_details_id"), table_name="at_bat_details")
    op.drop_table("at_bat_details")
    op.drop_index(
        op.f("ix_player_game_summary_player_name"), table_name="player_game_summary"
    )
    op.drop_index(op.f("ix_player_game_summary_id"), table_name="player_game_summary")
    op.drop_table("player_game_summary")
    op.drop_index(
        op.f("ix_player_season_stats_player_name"), table_name="player_season_stats"
    )
    op.drop_index(op.f("ix_player_season_stats_id"), table_name="player_season_stats")
    op.drop_table("player_season_stats")
    op.drop_index(op.f("ix_game_schedules_id"), table_name="game_schedules")
    op.drop_index(op.f("ix_game_schedules_game_id"), table_name="game_schedules")
    op.drop_table("game_schedules")
    op.drop_index(op.f("ix_game_results_id"), table_name="game_results")
    op.drop_index(op.f("ix_game_results_game_date"), table_name="game_results")
    op.drop_index(op.f("ix_game_results_cpbl_game_id"), table_name="game_results")
    op.drop_table("game_results")
    # ### end Alembic commands ###
