# .github/workflows/ci.yml

name: Python CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies for Playwright
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest requests pip-audit

      - name: Install Playwright Browsers
        run: |
          playwright install chromium --with-deps

      - name: Scan for vulnerabilities
        run: |
          pip-audit -r requirements.txt

      - name: Lint and Format Check
        run: |
          ruff check .

      - name: Run Unit and Integration Tests
        env:
          DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb
          DRAMATIQ_BROKER_URL: redis://localhost:6379/0
          REDIS_CACHE_URL: redis://localhost:6379/1
          API_KEY: test-ci-key
          TARGET_TEAM_NAME: "台鋼雄鷹"
          TARGET_TEAMS: '["台鋼雄鷹"]'
          TARGET_PLAYER_NAMES: '["王柏融","魔鷹","吳念庭"]'
        run: |
          pytest -m "not e2e and not canary"

      - name: Run E2E Tests
        env:
          DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb
          DRAMATIQ_BROKER_URL: redis://localhost:6379/0
          REDIS_CACHE_URL: redis://localhost:6379/1
          API_KEY: test-ci-key
          PORT: 8000
          E2E_TEST_MODE: "true"
          TARGET_TEAM_NAME: "台鋼雄鷹"
          TARGET_TEAMS: '["台鋼雄鷹"]'
          TARGET_PLAYER_NAMES: '["王柏融","魔鷹","吳念庭"]'
        run: |
          echo "Starting Web server..."
          uvicorn app.main:app --host 0.0.0.0 --port $PORT > web.log 2>&1 &
          python - <<'EOF'
          import os, time, requests
          port = os.getenv("PORT", "8000")
          url = f"http://localhost:{port}/docs"
          for i in range(20):
              try:
                  if requests.get(url).status_code == 200:
                      print("Web Server is up!")
                      exit(0)
              except requests.ConnectionError: pass
              print(f"Waiting for Web server... ({i+1}/20)")
              time.sleep(1)
          print("Web Server did not start in time."); exit(1)
          EOF

          echo "Starting Worker service with xvfb..."
          xvfb-run dramatiq app.workers:redis_broker app.workers --processes 2 > worker.log 2>&1 &
          sleep 5
          echo "Worker service started."

          pytest tests/e2e

      - name: Display logs on failure
        if: failure()
        run: |
          echo "--- Web Server Logs ---"
          cat web.log || echo "web.log not found"
          echo "\n--- Worker Logs ---"
          cat worker.log || echo "worker.log not found"

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: build-and-test # 確保在 build-and-test 成功後才執行
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # 僅在推送至 main 分支時執行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set Fly.io Secrets Dynamically
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SECRETS_JSON: ${{ toJSON(secrets) }}
        run: |
          # 使用 jq 工具解析 JSON，篩選出所有以 'PROD_' 開頭的 secrets
          SECRETS_TO_SET=$(echo "$SECRETS_JSON" | jq -r 'to_entries[] | select(.key | startswith("PROD_")) | "\(.key | ltrimstr("PROD_"))=\(.value)"')

          if [[ -n "$SECRETS_TO_SET" ]]; then
            echo "Staging secrets on Fly.io..."
            # 【修改】加入 --stage 旗標，讓 secrets 在下次部署時才生效，避免立即重啟
            echo "$SECRETS_TO_SET" | xargs flyctl secrets set --stage --app cpbl-takao-today-be
          else
            echo "No secrets with PROD_ prefix found to set."
          fi

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --app cpbl-takao-today-be
