name: Schedule Worker Start/Stop

on:
  schedule:
    # 使用 CRON 語法設定排程
    # 請根據你的爬蟲執行時間調整
    - cron: "0 13 * * *" # 啟動時間
    - cron: "0 14 * * *" # 關閉時間

jobs:
  manage-worker:
    name: Start or Stop Worker Machine
    runs-on: ubuntu-latest

    steps:
      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          # --- 修正 ---
          # 使用 GITHUB_PATH 將 flyctl 的路徑加入到後續所有步驟的環境變數中
          echo "/home/runner/.fly/bin" >> $GITHUB_PATH

      - name: Determine Action (Start or Stop)
        id: get_action
        run: |
          if [[ "${{ github.event.schedule }}" == "0 13 * * *" ]]; then
            echo "action=start" >> $GITHUB_OUTPUT
          else
            echo "action=stop" >> $GITHUB_OUTPUT
          fi

      - name: Run flyctl command
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          MACHINE_ID="e82541dc03ded8"
          ACTION=${{ steps.get_action.outputs.action }}

          echo "Executing '${ACTION}' on machine ${MACHINE_ID}..."
          fly machine ${ACTION} ${MACHINE_ID} --app cpbl-takao-today-be
          echo "Command executed."
