name: Schedule Worker Start/Stop

on:
  schedule:
    # 使用 CRON 語法設定排程
    - cron: "0 21 * * *" # 啟動時間
    - cron: "0 22 * * *" # 關閉時間

jobs:
  manage-worker:
    name: Start or Stop Worker Machine
    runs-on: ubuntu-latest

    steps:
      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"

      - name: Determine Action (Start or Stop)
        id: get_action
        run: |
          # 根據觸發的 CRON 時間來決定是執行 start 還是 stop
          if [[ "${{ github.event.schedule }}" == "0 21 * * *" ]]; then
            echo "action=start" >> $GITHUB_OUTPUT
          else
            echo "action=stop" >> $GITHUB_OUTPUT
          fi

      - name: Run flyctl command
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          MACHINE_ID="e82541dc03ded8"
          ACTION=${{ steps.get_action.outputs.action }}

          echo "Executing '${ACTION}' on machine ${MACHINE_ID}..."
          fly machine ${ACTION} ${MACHINE_ID} --app cpbl-takao-today-be
          echo "Command executed."
